### ISSUE TITLE
Remote I/O error

### ISSUE THREAD

**Issue by butlerjoey** [Sanderi44/Lidar-Lite#9]
I'm just trying to run the simple test code, but keep getting the error message below.  I know the Lidar Lite and Pi are setup correctly, and I've turned on the I2C interface and enabled the I2C tools.  I'm new to this, and have been stuck here for quite a while now.  Any idea what might be wrong?

------------------------------------
Traceback (most recent call last):
  File "/home/pi/Lidar-Lite/python/test.py", line 9, in <module>
    print (lidar.getDistance())
  File "/home/pi/Lidar-Lite/python/lidar_lite.py", line 38, in getDistance
    self.writeAndWait(self.distWriteReg, self.distWriteVal)
  File "/home/pi/Lidar-Lite/python/lidar_lite.py", line 24, in writeAndWait
    self.bus.write_byte_data(self.address, register, value);
OSError: [Errno 121] Remote I/O error
------------------------------------

**Comment by laksh-lp** [comment]
were u able to solve the error ? even i am facing the same issue ..

**Comment by Sanderi44** [comment]
Hi there, please check out this answer which is related to i2c-tools. Hopefully this can help. https://github.com/PiSupply/PaPiRus/issues/124#issuecomment-306699589

**Comment by neuberfran** [comment]
![image](https://user-images.githubusercontent.com/38701397/56006645-21a36f00-5cac-11e9-8383-69f5359c3a0e.png)
anyone

**Comment by Sanderi44** [comment]
Can you do a bit of debugging here?  Are you sure that the device is connected properly? Can you confirm this by checking "sudo i2cdetect -y 1" to see that the device is recognized on that address?

https://learn.adafruit.com/adafruits-raspberry-pi-lesson-4-gpio-setup/configuring-i2c
